server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: database
    url: jdbc:mysql://localhost:3306/remind_me?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
#mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/xml/*.xml
  type-aliases-package: com.sssr.assets.entity


